/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziplinegames_moai_CommonSign */

#ifndef _Included_com_ziplinegames_moai_CommonSign
#define _Included_com_ziplinegames_moai_CommonSign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziplinegames_moai_CommonSign
 * Method:    validateSign
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ziplinegames_moai_CommonSign_validateSign
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
